ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS website_verify_token VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS website_verified BOOLEAN DEFAULT false;
